fix: hack to try to get jobs building again

diff --git a/devtools-ci-index.yaml b/devtools-ci-index.yaml
--- a/devtools-ci-index.yaml
+++ b/devtools-ci-index.yaml
@@ -125,18 +125,13 @@
     description: |
       {jobdescription}
     node: "{ci_project}"
-    wrappers:
-        - npm-build-deliver-creds
     properties:
         - github:
             url: https://github.com/{git_organization}/{git_repo}/
-        - inject:
-            properties-content: |
-               JENKINS_URL=https://ci.centos.org
     scm:
         - git:
             url: https://github.com/{git_organization}/{git_repo}.git
-            shallow_clone: false
+            shallow_clone: true
             branches:
                 - {branch}
     triggers:
@@ -163,6 +158,43 @@
             fi
             exit $rtn_code
 
+- job-template: &job_template_build_branch_defaults
+    name: 'job_template_build_branch_defaults'
+    description: |
+      {jobdescription}
+    node: "{ci_project}"
+    properties:
+        - github:
+            url: https://github.com/{git_organization}/{git_repo}/
+    scm:
+        - git:
+            url: https://github.com/{git_organization}/{git_repo}.git
+            shallow_clone: true
+            branches:
+                - {branch}
+    triggers:
+        - github
+    builders:
+        - shell: |
+            # testing out the cico client
+            set +e
+            export CICO_API_KEY=$(cat ~/duffy.key )
+            read CICO_hostname CICO_ssid <<< $(cico node get -f value -c ip_address -c comment)
+            sshopts="-t -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -l root"
+            ssh_cmd="ssh $sshopts $CICO_hostname"
+            env > jenkins-env
+            $ssh_cmd yum -y install rsync
+            rsync -e "ssh $sshopts" -Ha $(pwd)/ $CICO_hostname:payload
+            $ssh_cmd -t "cd payload && {ci_cmd}"
+            rtn_code=$?
+            if [ $rtn_code -eq 0 ]; then
+              cico node done $CICO_ssid
+            else
+              # fail mode gives us 12 hrs to debug the machine
+              curl "http://admin.ci.centos.org:8080/Node/fail?key=$CICO_API_KEY&ssid=$CICO_ssid"
+            fi
+            exit $rtn_code
+
 - job-template:
     name: '{ci_project}-{git_repo}-build-master'
     scm:
@@ -181,7 +213,7 @@
             shallow_clone: true
             branches:
                 - master
-    <<: *job_template_build_defaults
+    <<: *job_template_build_branch_defaults
 
 - job-template:
     name: '{ci_project}-{git_repo}-build-master-coverage'
