f8a: handle multiple deployments at once (#266)

diff --git a/devtools-ci-index.yaml b/devtools-ci-index.yaml
--- a/devtools-ci-index.yaml
+++ b/devtools-ci-index.yaml
@@ -453,8 +453,8 @@
             GIT_ORGANIZATION={git_organization}
             UPSTREAM_GIT_COMMIT=$GIT_COMMIT
             SAAS_GIT={saas_git}
-            DEPLOYMENT_UNIT={deployment_unit}
-            DEPLOYMENT_CONFIG={deployment_config}
+            DEPLOYMENT_UNITS={deployment_units}
+            DEPLOYMENT_CONFIGS={deployment_configs}
             CICO_HOSTNAME=$CICO_hostname
             CICO_SSID=$CICO_ssid
             EOF
@@ -486,9 +486,9 @@
           name: SVC_NAME
           default: none
       - string:
-          name: DEPLOYMENT_UNIT
+          name: DEPLOYMENT_UNITS
       - string:
-          name: DEPLOYMENT_CONFIG
+          name: DEPLOYMENT_CONFIGS
       - string:
           name: CICO_HOSTNAME
       - string:
@@ -510,29 +510,35 @@
             env > jenkins-env
 
             export GIT_COMMIT=$UPSTREAM_GIT_COMMIT
-            export GIT_REPO=$DEPLOYMENT_UNIT
+
 
             {saasherder_prepare}
             export DEVSHIFT_TAG_LEN=7
-            # Deploy preview
-            {saasherder_deploy}
+            for DEPLOYMENT_UNIT in $DEPLOYMENT_UNITS; do
+                export GIT_REPO=$DEPLOYMENT_UNIT
+                # Deploy preview
+                {saasherder_deploy}
+            done
 
             export CICO_API_KEY=$(cat ~/duffy.key )
             gc() {{
                 rtn_code=$?
-                if [ $rtn_code -ne 0 ]; then
-                    # Tests failed, rollback
-                    oc rollback dc/$DEPLOYMENT_CONFIG -n $PRJ_NAME
-                fi
+                for DEPLOYMENT_CONFIG in $DEPLOYMENT_CONFIGS; do
+                    if [ $rtn_code -ne 0 ]; then
+                        # Tests failed, rollback
+                        oc rollback dc/$DEPLOYMENT_CONFIG -n $PRJ_NAME || :
+                    fi
+                done
                 cico node done $CICO_SSID || :
                 exit $rtn_code
             }}
             trap gc EXIT SIGINT
             set -e
 
-            # Wait for deployment to start and then wait for it to be ready (yeah, this is pretty frafile)
+            # Wait for deployment to start and then wait for it to be ready (yeah, this is pretty fragile)
             sleep 5
-            oc logs -f dc/$DEPLOYMENT_CONFIG -n $PRJ_NAME
+            LAST_DC=${{DEPLOYMENT_CONFIGS##* }}
+            oc logs -f dc/$LAST_DC -n $PRJ_NAME
 
             # Run E2E tests
             sshopts="-t -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -l root"
@@ -1479,5 +1485,5 @@
             ci_project: 'devtools'
             ci_cmd: '/bin/bash cico_build_deploy.sh'
             saas_git: saas-analytics
-            deployment_unit: 'fabric8-analytics-pgbouncer'
-            deployment_config: 'bayesian-pgbouncer'
+            deployment_units: 'fabric8-analytics-pgbouncer'
+            deployment_configs: 'bayesian-pgbouncer'
