Change job template.

diff --git a/devtools-ci-index.yaml b/devtools-ci-index.yaml
--- a/devtools-ci-index.yaml
+++ b/devtools-ci-index.yaml
@@ -2696,6 +2696,78 @@
                           vault-key: '{service_account_client_secret_cred}'
     <<: *contract_tests_provider_template
 
+- saas_prcheck_rhche_template: &saas_prcheck_rhche_template
+    name: 'saas_prcheck_rhche_template'
+    description: |
+      {jobdescription}
+    node: "{ci_project}"
+    concurrent: false
+    properties:
+        - github:
+            url: https://github.com/{git_organization}/{git_repo}/
+        - build-discarder:
+            days-to-keep: '{discarder_days}'
+            num-to-keep: '{discarder_num}'
+    scm:
+        - git-scm:
+            git_url: https://{github_user}@github.com/{git_organization}/{git_repo}.git
+            git_basedir: ''
+    triggers:
+        - githubprb:
+            github_hooks: '{github_hooks}'
+    builders:
+        - shell: |
+            # testing out the cico client
+            set +e
+            cp ~/artifacts.key .
+            export CICO_API_KEY=$(cat ~/duffy.key )
+            # get node
+            n=1
+            while true
+            do
+                cico_output=$(cico node get -f value -c ip_address -c comment)
+                if [ $? -eq 0 ]; then
+                    read CICO_hostname CICO_ssid <<< $cico_output
+                    if  [ ! -z "$CICO_hostname" ]; then
+                        # we got hostname from cico
+                        break
+                    fi
+                    echo "'cico node get' succeed, but can't get hostname from output"
+                fi
+                if [ $n -gt 15 ]; then
+                    # give up after 15 tries
+                    echo "giving up on 'cico node get'"
+                    exit 1
+                fi
+                echo "'cico node get' failed, trying again in 60s ($n/15)"
+                n=$[$n+1]
+                sleep 60
+            done
+            sshopts="-t -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -l root"
+            ssh_cmd="ssh $sshopts $CICO_hostname"
+
+            cp ~/cico-tools/env-toolkit .
+            ./env-toolkit dump -f jenkins-env.json
+            env > jenkins-env
+
+            $ssh_cmd yum -y install rsync
+
+            rsync -e "ssh $sshopts" -Ha $(pwd)/rhche/ $CICO_hostname:payload \
+            && /usr/bin/timeout {timeout} $ssh_cmd -t "cd payload && {ci_cmd}"
+            rtn_code=$?
+            if [ $rtn_code -eq 0 ]; then
+                cico node done $CICO_ssid
+            else
+                if [[ $rtn_code -eq 124 ]]; then
+                   echo "BUILD TIMEOUT";
+                   cico node done $CICO_ssid
+                else
+                    # fail mode gives us 12 hrs to debug the machine
+                    curl "http://admin.ci.centos.org:8080/Node/fail?key=$CICO_API_KEY&ssid=$CICO_ssid"
+                fi
+            fi
+            exit $rtn_code
+
 - job-template: 
     name: '{ci_project}-{git_repo}-pr-check-rh-che'  
     scm:  
@@ -2737,7 +2809,7 @@
                       valut-key: 'username'
                     - env-var: 'EMAIL'
                       valut-key: email
-    <<: *job_template_defaults
+    <<: *saas_prcheck_rhche_template
 
 
 - project:
