Added EE test (#139)

diff --git a/devtools-ci-index.yaml b/devtools-ci-index.yaml
--- a/devtools-ci-index.yaml
+++ b/devtools-ci-index.yaml
@@ -623,6 +623,68 @@
         - archive:
             artifacts: ./perfcake-7.4/perfcake-chart
 
+- job:
+    name: 'devtools-test-end-to-end'
+    defaults: global
+    node: devtools
+    properties:
+        - github:
+            url: https://github.com:fabric8io/fabric8-ui
+    scm:
+        - git:
+            url: https://github.com:fabric8io/fabric8-ui.git
+
+            shallow_clone: true
+            branches:
+                - master
+    triggers:
+        - timed: '30 08,12,16,20 * * *'
+    wrappers:
+        - credentials-binding:
+            - username-password-separated:
+                credential-id: 9d2a233c-4350-49ab-983d-5b8d0de95f44
+                username: EE_TEST_USERNAME
+                password: EE_TEST_PASSWORD
+    builders:
+        - shell: |
+            set +e
+            set +x
+            env > jenkins-env
+            cat $creds_config_file >> jenkins-env
+            export CICO_API_KEY=$(cat ~/duffy.key )
+            # get node
+            n=1
+            while true
+            do
+                cico_output=$(cico node get -f value -c ip_address -c comment)
+                if [ $? -eq 0 ]; then
+                    read CICO_hostname CICO_ssid <<< $cico_output
+                    if  [ ! -z "$CICO_hostname" ]; then
+                        # we got hostname from cico
+                        break
+                    fi
+                    echo "'cico node get' succeed, but can't get hostname from output"
+                fi
+                if [ $n -gt 5 ]; then
+                    # give up after 5 tries
+                    echo "giving up on 'cico node get'"
+                    exit 1
+                fi
+                echo "'cico node get' failed, trying again in 60s ($n/5)"
+                n=$[$n+1]
+                sleep 60
+            done
+            echo 'Using Host' $CICO_hostname
+            set -x
+            sshopts="-t -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -l root"
+            ssh_cmd="ssh $sshopts $CICO_hostname"
+            $ssh_cmd yum -y install rsync
+            rsync -e "ssh $sshopts" -Ha $(pwd)/ $CICO_hostname:payload
+            $ssh_cmd -t "cd payload && /bin/bash cico_run_EE_tests.sh $EE_TEST_USERNAME $EE_TEST_PASSWORD"
+            rtn_code=$?
+            cico node done $CICO_ssid
+            exit $rtn_code
+
 - wrapper:
     name: generator_credentials_wrapper
     wrappers:
@@ -872,3 +934,5 @@
             ci_project: 'devtools'
             ci_cmd: '/bin/bash cico_build_deploy.sh'
             svc_name: catapult
+
+
